tests:
  - name: "Test Get User"
    endpoint: "/user/1"
    method: "GET"
    expected_status: 200
  - name: "Test Get Nonexistent User"
    endpoint: "/user/9999"
    method: "GET"
    expected_status: 404