tests:
  - name: "Test Get User"
    endpoint: "/api/users/3"
    method: "GET"
    expected_status: 200
  - name: "Test Get Nonexistent User"
    endpoint: "api/users/9999"
    method: "GET"
    expected_status: 404